### ISSUE TITLE
Add start and end date for each survey in the overview page

### ISSUE THREAD

**Issue by mmuller** [instedd/surveda#1123]
Requested by Jennifer Sabatier: 

> For reporting for Bloomberg I need to get the total number of surveys sent out in June via every and all of the different testing we did.  Instead of clicking through the web app is there a backdoor I can access via R so I can do this more efficiently?

**Comment by manumoreira** [comment]
Add start and end date for each survey in the overview page

**Comment by anaPerezGhiglia** [comment]
* Add finished_at column. Migrate it with updated_at if is a final one already.
* Update finished_at when survey is finished.
* Show: _Running since `{started_at}`_ or _Running since `{started_at}` until `{finished_at}`_

**Comment by anaPerezGhiglia** [comment]
@manumoreira 
How do we want to display this? 
Should  end_date be exposed when survey is terminated because it was cancelled or there was another error (such as deleting the channel)
Currently, when the survey is terminated, survey status shows: 
 * If it was terminated ok: ‘_Completed_’
 * If it was cancelled: ‘_Cancelled_’
 * It there was an error: ‘_Failed_’

How should the wording be? Something as ‘_Completed. Run from <start_date> to <end_date>_’?  Something that should be noted is that this might look awkward for surveys started and ended at in the same day

**Comment by manumoreira** [comment]
@anaPerezGhiglia your suggestions sound OK. 
end_date must be shown when the survey is terminated, Showing the status before the dates will help.
About one-day surveys, showing the same date twice is not nice, but not too bad. Do you have any suggestion for this?

**Comment by anaPerezGhiglia** [comment]
@manumoreira 
how about displaying something as _'Ran only on <survey_date>'_ when the survey was started and ended in the same day?

**Comment by mmuller** [comment]
Working properly in version 9a760ad
