### ISSUE TITLE
Overview not loading in a particular survey

### ISSUE THREAD

**Issue by manumoreira** [instedd/surveda#1471]
In this survey the overview doesn't load 
https://surveda-mw.org/projects/2/surveys/216

**Comment by matiasgarciaisaia** [comment]
The issue was caused by a quota definition that segmented by ages. If the delimiters are `18, 30, 80, 120`, Surveda will create the buckets `18-29`, `30-79`, and `80-119`. When somebody replies an age of `120`, it's a valid response, but it doesn't match any bucket - and that makes the stats return an empty answer that the UI doesn't properly handle.

So we have to make the UI handle the stats' empty answer, but we also have to fix the buckets definition. For the aforementioned example, we should create the last bucket as `80-120`, and mark every respondent that doesn't fit any bucket as `ineligible`.

**Comment by bcardiff** [comment]
* When editing quotas, for numeric values when inputting 10,20,30 those numbers should be cutting points the ranges should always be: <10, 10-19, 20-30, 30< so the buckets will be any of those 4.
* Bonus point: create nice defaults based on `min,delimiters,max`. If there is a `max`, the semantic of the buckets need to be `+/-1` adjusted to match the same buckets that are expressed in the answer.
* Design issue: how accept refusals are handled? because there is no number to use in bucket. Solution: do not allow using that variable in the quota.

**Comment by ysbaddaden** [comment]
This bug is resurfacing in different production servers. There is a recent example in the LK instance with Survey id=368, and a few occurrences in other instances.
