### ISSUE TITLE
Call duration should include only minutes and seconds

### ISSUE THREAD

**Issue by mmuller** [instedd/surveda#1518]
Version 4f50b9c

![image](https://user-images.githubusercontent.com/518152/65257934-6c85a600-dad8-11e9-8772-89abc08e00d4.png)

**Comment by waj** [comment]
We decided to show the `total_call_time` column with a format like: **23m 17s**

To acomplish this is better to store the value in the database in seconds (instead of minutes). But in order to be backward compatible and avoid a huge migration let's do this:
  * From now on store the call time in seconds within the stats as `total_call_time_seconds`
  * When the CSV is exported look for `total_call_time_seconds` and `total_call_time` (currently stored in minutes) in that order and use the first one available. The output format is the same. The output column should still be `total_call_time`.

**Comment by mmuller** [comment]
Working properly in version 2de3bab
