### ISSUE TITLE
Surveys cannot be removed

### ISSUE THREAD

**Issue by mmuller** [instedd/surveda#1560]
Version d6b2b6b

When pressing `Delete` an internal server error is thrown.

**Comment by bcardiff** [comment]
@mmuller the fix applies to running surveys only, but from the code these are all the survey status:

* running
* cancelling
* terminated
* stalled
* rejected
* failed
* active
* completed
* cancelled
* not_ready

I would expect that the newly `cancelling` status should not be able to be deleted. Since queues need to be emptied while it is on that state.

@manumoreira do you expect any other input for other states?

**Comment by mmuller** [comment]
@bcardiff I could reproduce this issue using the following survey status:

- running
- failed
- cancelled

Should I open another issue to deal with `failed` and `cancelled` status?

**Comment by mmuller** [comment]
Working properly in version 3e05578
