### ISSUE TITLE
[Histogram] Same respondent appears twice

### ISSUE THREAD

**Issue by mmuller** [instedd/surveda#1611]
There are 10 respondents.
10 respondents received the first contact attempt.
One of them will receive the first retry.
The histogram shows 10 respondents in the initial stack and 1 respondent placed in the first retry.

![image](https://user-images.githubusercontent.com/518152/72361667-a35b7980-36d0-11ea-886b-ddf7c0ad42f8.png)

![image](https://user-images.githubusercontent.com/518152/72370408-f1787900-36e0-11ea-9301-966b76e2d4db.png)

This issue was also reproduced using the following:
survey_id: 2502
caller_id: 99925
call_id: 222802
call_id: 222803

**Comment by anaPerezGhiglia** [comment]
Friday 2020-01-17 update (co-auth with @mmuller )

**Update:** this does not happen consistently, in some surveys happens in others not.
**Description:**
verboice called 2 times to the same respondent, the failure is `Call Rejected` for the first call, and for the second it is `Interworking, unspecified`. The distance between the calls is 1 minute. 
On the one hand, the histogram is not removing the respondent from the first bar; on the other hand, verboice is calling the same respondent after 1 minute
The respondent called twice has for retry_stat_id the id corresponding to the second-attempt slot

\* This also happens with nuntium

![image](https://user-images.githubusercontent.com/13237343/72745216-009e7180-3b8e-11ea-8ff7-17022a2320dc.png)

**Comment by anaPerezGhiglia** [comment]
This seems to happen beacause there is a concurrency problem in Surveda. When this happens, `Ecto.StaleEntryError` in respondent entity is raised

The foundation of this issue seems to be that this error is being raised when starting new respondents. Since respondents are being started sequentially, when one fails the consequent ones are not started
Apparently this is happening after enqueuing calls/sms to verboice/nuntium, but before changing respondent's state


The flow would be:
 - respondent **A** has `state: pending`
 - respondent **A** is selected for starting
 - surveda enqueues respondent **A** in verboice/nuntium
 - respondent **A** is added to the retries_histogram
 - surveda tries to update respondent and fails with an uncaught exception - Ecto.StaleEntryError (respondent.state was not updated, thus is still `pending`)

In the next `Broker.poll` (scheduled once a minute), the respondent **A** still has `state: pending` so is eligible for starting so:
 - respondent **A** is selected for starting (again)
 - surveda enqueues respondent **A** in verboice/nuntium (again)
 - respondent **A** is added to the retries_histogram (again)
 - surveda updates respondent state successfully 
 - surveda continues updating the following respondents

 The scenario above would explain why:
 - a respondent is queued two times with one minute difference in the corresponding channel: is the interval between each `Broker.poll`
 - the respondent has +1 `stats.attempt`: when starting a new flow, an attempt is added to the stats, not set in 1.
 - the histogram shows +1 respondents: when adding a new respondent to the histogram, surveda doesn't check if it has already a `retry_stat_id` (since it shouldn't since is new to the histogram)
 	- gets the slot where the respondent belongs (taking into account `respondent.stats.attempt`)
 	- +1 to the new slot (without -1 to the oldest slot)

----

Inspecting the application log we can see that a survey - that has only 5 respondents - starts to initialize them two times and a `StaleEntryError` is raised in the middle. 

By the _up_to # of respondents_ we can assume that only 3 respondents where started the first time
![image](https://user-images.githubusercontent.com/13237343/72748087-17949200-3b95-11ea-9d5a-1eaea3a07b6c.png)

**Comment by mmuller** [comment]
Working properly in version 672562a
