### ISSUE TITLE
Collaborator IP address is displayed in activity log 

### ISSUE THREAD

**Issue by mmuller** [instedd/surveda#1688]
Found in version 3ffaf2e

If the user has no name, their IP address is displayed in the Activity log. 
We should display the user email when there is no user name.

![image](https://user-images.githubusercontent.com/518152/78814316-ce3e2c80-79a4-11ea-9525-46a9577b0afe.png)

It may be related to #1555

**Comment by bcardiff** [comment]
I'm not sure if username are optionals. In stg we use guisso so there is no input from the user regarding that. In prod guisso is not used and the form has a name.

If username are blank only because of guisso I would say that from the backend the first part of the email should be used as such.

If username are optional as a whole in surveda, then showing the whole email is good enough for now.

**Comment by aeatencio** [comment]
I've just signed up in STG without a username. So, I assume it's optional, and I'll proceed by showing the whole email when the username doesn't exist.

Because the email isn't optional, if I'm not missing something, the IP won't be shown anymore in the username field of the activity log.

@bcardiff please let me know if I'm on the wrong track.

**Comment by mmuller** [comment]
Working properply in version 8fa4cc0
