### ISSUE TITLE
Refreshing the session when the simulation is ended throws a JS error

### ISSUE THREAD

**Issue by mmuller** [instedd/surveda#1985]
**Steps to reproduce:**

1. Select the phone mode
2. Start a simulation
3. Complete the "Survey"
4. Refresh the session

**Obtained:**
- A JS error is thrown

**Error details:**
https://sentry.io/organizations/instedd/issues/2761590658/?project=105692&referrer=alert_email

**Comment by ysbaddaden** [comment]
Yes, I stated that in the PR or one of the IVR simulator issue: we need minimal user interaction in the page (e.g. a click) _before_ we can start playing any audio file.

Since this is a React application, it will work on the first simulation, because we interacted with the modal to start the simulation, but "refresh the simulation" means reloading the page, which will immediately start the simulation, before we could interact with anything, which fails... until we start responding to a question.

There are two possible workarounds, not mutually exclusive:

1. add a [refresh] button to the toast, to restart the simulation without reloading the page;
2. display a splash with a button to start the simulation, either when we can't play audio or always; something like "picking up the phone".

ping @diegoliberman @manumoreira

**Comment by manumoreira** [comment]
Option 1 looks good to me

**Comment by ysbaddaden** [comment]
Here are some possible buttons:

![Capture d'écran du 2021-11-15 17 44 27@2x](https://user-images.githubusercontent.com/47380/141826970-053c93bf-41c0-4354-a502-45274c06c5fe.jpeg)

![Capture d'écran du 2021-11-15 17 44 48@2x](https://user-images.githubusercontent.com/47380/141826975-0a929a8c-7ce6-4653-b3dc-241234dd96ad.jpeg)

I'll welcome other suggestions :ear:

**Comment by diegoliberman** [comment]
@ysbaddaden I think the first option has more contrast and ends up being more clear.  I was hesitating if we should use the blue color (for the button background) used for most submit button in this app, but as this action is not an actual submit of a form, I think it's appropiate to use a different style.

**Comment by manumoreira** [comment]
@ysbaddaden I would doubt, green is the surveda's default color, that's the right one for the restart button

**Comment by ysbaddaden** [comment]
Just merged in master. It should be ready to deploy to staging soon.
