### ISSUE TITLE
Missing bucket error when calculating percentages

### ISSUE THREAD

**Issue by ysbaddaden** [instedd/surveda#1999]
A bug reminiscent of #1471 is happening in production servers.

There is a recent example in the LK instance for the survey id=368 (see [SURVEDA-LK-2X](https://sentry.io/organizations/instedd/issues/1654548537/?project=1263912)):

> **function nil.quota/0 is undefined or private**

The bug happens in [Ask.RespondentController](https://github.com/instedd/surveda/blob/master/web/controllers/respondent_controller.ex#L375-L381). We're trying to find a bucket for a group but there is no such bucket, so Surveda crashes when it tries to calculate the group's percentage. I assume we don't validate properly that the configured buckets match the whole range, or we're missing a fallback solution, or a proper error reporting?

**Comment by manumoreira** [comment]
I think this is the same as #1471 
It is happening in surveda-lk but not in a running survey, the error reported in sentry comes from the user trying to see the overview of an old survey.
@matiasgarciaisaia did some progress in #1471 long ago, but the issue is still open. AFAIR the `fixes` prevent the issue to happen again when configuring a survey but the old surveys will still crash, con you confirm this, please?

**Comment by matiasgarciaisaia** [comment]
From what I recall, yes - the fixes were to prevent causing the underlying error (a respondent without a bucket due to the ranges being non-exhaustive) again, but they don't fix the presentation/view bug.

I don't have enough context on the top of my mind to make a call on whether we should make the view support those cases (ie, if the tool should support respondents without buckets in bucketed surveys) or if we should try to fix the inconsistent data and move on.

----

> The bug happens in [Ask.RespondentController](https://github.com/instedd/surveda/blob/master/web/controllers/respondent_controller.ex#L375-L381).

Beware linking to files via changing references like the `master` branch - line 375 of that file can be _a completely different thing_ in a month. Referencing the current file's commit is more future proof: https://github.com/instedd/surveda/blob/5437ad6988ecb8e23ee591d32808479818e313ce/web/controllers/respondent_controller.ex#L375-L381

**Comment by ysbaddaden** [comment]
Manually fixing the buckets for the failing surveys may be enough to fix the issue. As soon as the bucket exists for the group, then we should be able to calculate the quotas, and display the resulsts.

**Comment by diegoliberman** [comment]
Let's dedicate 2h to analyze how long could it take to solve it for everyone.  This is happening for old surveys only, and it's happening with very little frequency.  Hence right now we will invest time only if the solutions is easy.

**Comment by ysbaddaden** [comment]
@manumoreira @diegoliberman The corrections made by Mati are indeed fixing the issue, but looking at the discussion in #1471 it may not be the business solution to choose. For example:

If I have a numeric value in the 10-120 range and create a quota for 10,30,50,120 then I'll have the following quota ranges: 10-29, 30-49 and 50-119, despite the range being 10-120, because we _always_ use an exclusive end, hence skip the last value for each range. This is indeed a bug: we're leaving out a value when we shouldn't.

Mati's proposal is making the last range become inclusive, so it becomes 50-120. It also introduces another fix, such as making sure that an out of order input such as 10,120,50,30 is always processed as 10,30,50,120 which is a good idea.

The last comment by Brian pinpoints that maybe we should introduce a 120+ range... but that's a weird take because we do specify the last value of the numeric range, so we aim to include it, just like we included the lower bound (10) and expect it to be used.

**Last weirdness:** the UI allows to not bucket the whole range!

For example I can say 30,50,100 and we'll create the 30-49 and 50-99 buckets, leaving 10-29 and 100-120 out. Since those are cutoff quotas, maybe we don't need to enforce any quota for the <30 and >100? I have a feeling that doing so will just have the same impact -> error.

**Comment by mmuller** [comment]
Now in version https://github.com/instedd/surveda/commit/b6ec048fc804383efaf1ce3e656a901e5d0e5688, the last values are not left out.
