### ISSUE TITLE
Simplify ChannelBroker state persistence

### ISSUE THREAD

**Issue by aeatencio** [instedd/surveda#2133]
Save to DB on change and recover from DB on init
Reason: early optimization with difficult testing

**Comment by ysbaddaden** [comment]
**Alternative**: disable the state persistence. We'll see if we eventually rework the state to live in the database (so we can have multiple servers handling the queues). Maybe we'd only have to return the state when the channel broker crashes and feed it back when we restart it (full memory).

**Comment by leandroradusky** [comment]
The actual implementation saves to DB only after a series of operations (actually, every 100 operations & on timeout).
The supervisor recovers the state (`:one_for_one` strategy) from memory if it is there, from DB otherwise, else from scratch. 

After some testing, this appears to be working ok. We can play with the numbers to make this work as desired (i.e. never save to DB if that is what we want) but following this thread appears that what we have is OK.

**Comment by ysbaddaden** [comment]
Current action: let's disable saving for now. I had issues on local when stopping surveda while a survey is running and the channel broker would crash on restart (taking surveda down).
