### ISSUE TITLE
Integer variable quota buckets should be exhaustive

### ISSUE THREAD

**Issue by matiasgarciaisaia** [instedd/surveda#2318]
We've seen #1471 happen time and time again: when using quotas, if a respondent doesn't match any of the existing quotas, the survey progress calculation gets broken.

When setting the quota buckets (as of 0.37.2), Surveda asks the survey editor for the buckets limits of integer variables, and creates ranges between them. For example, for an `Age` variable with range `0-110`, the delimiters `18,30,45,100` yield the buckets `18-29`, `30-44`, `45-100`. **The values <18 and >100 don't belong to any bucket.**

Instead, Surveda should guarantee every value belongs to a bucket, creating extra buckets for the values below the minimum delimiter, and above the maximum. So, in this case, the resulting buckets should be `<18`, `18-29`, `30-44`, `45-100`, `>100`.

We should probably avoid making the implicit boundaries of the intervals explicit (ie, make the first bucket `0-17`) because they can change in the quex before the survey is started (and, also, because the user doesn't care about them - if they would care, they would include that value as a delimiter).

**Comment by manumoreira** [comment]
I've been testing this feature here https://surveda-stg.instedd.org/projects/383/surveys/4202 and it seems like the fact of having quotas with 0 makes the survey endless.
In this case quotas (with values > 0) are completed but the survey keeps polling respondents and never ends.
Maybe that's the expected behavior and the quotas should not allow to have 0 as value... then we should find another solution for this cases

**Comment by anaPerezGhiglia** [comment]
The misbehavior reported by Manu in the previous message is not related to this issue so I'm closing it
