### ISSUE TITLE
[Quiz] It would be helpful to clarify how a language must be selected.

### ISSUE THREAD

**Issue by mmuller** [instedd/surveda#595]
Now in version b86ae04 the user must click on the little arrow to select a language. Sometimes that arrow doesn't look clickable and the language selection is not very clear.

<img width="1404" alt="screen shot 2017-01-25 at 9 41 21 pm" src="https://cloud.githubusercontent.com/assets/518152/22315687/122e738e-e347-11e6-844e-17e77de21c2b.png">

**Comment by edjez** [comment]
Could it be autosuggested until replaced by a user?

On Jan 25, 2017, at 16:43, mmuller <notifications@github.com> wrote:

Now in version b86ae04
<https://github.com/instedd/ask/commit/b86ae04db567850740ca7316dd1ca80757c96071>
the language selection is not very clear.

[image: screen shot 2017-01-25 at 9 41 21 pm]
<https://cloud.githubusercontent.com/assets/518152/22315687/122e738e-e347-11e6-844e-17e77de21c2b.png>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/instedd/ask/issues/595>, or mute the thread

**Comment by manumoreira** [comment]
Already fixed
